### ISSUE TITLE
Getting a missing a template error for this request format and variant.

### ISSUE THREAD

**Issue by OmarZV** [5minpause/multiple-file-upload#12]
Holger thank you so much for your tutorial on multiple file upload. I was following along very well, but ran into an issue with respect to the Progress Bar. It doesn't seem to show and I get an actioncontroller error stating "missing a template for this request format and variant." I have listed my code below that I was hoping you can help me out with. 

**_form.html.erb**

    <%= form_for(item, html: { multipart: true }) do |f| %>
    <% if item.errors.any? %>
    <div class="field">
    <i class="fa fa-picture-o" aria-hidden="true"></i>
    <%= f.label :avatar, t('.upload_new_image') %>
    <%= f.file_field :avatar, multiple: true, name: 'item[avatar]' %>
    </div>
    <div class="actions">
    <%= f.submit "Create Item", :class => "btn btn-primary btn-md"%>
    </div>
    <% end %>
    <% # jquery upload template # %>
    <script id="template-avatar" type="text/x-tmpl"><div class="item">{%=o.name%}
    <div class="progress">
    <div class="progress-bar bar" style="width: 0%">
    </div>
    </div>
    </div>
    </script>

**create.js.erb (within my items folder)**

    <% if @item.new_record? %>
    alert('Failed');
    <% else %>
    $('h1').append("<%= j render(@item)  %> ");
    <% end %>

**items controller**

    def create         
    @item = current_user.items.create(item_params)
    end
    private
    def item_params
      params.require(:item).permit(:avatar)
    end

**imageavatar.js.coffee**

    jQuery ->
    $('#item_avatar').attr('name','item[avatar]')
    $('#new_item').fileupload
    dataType: 'script'
    add: (e, data) ->
      types = /(\.|\/)(gif|jpe?g|png|mov|mpeg|mpeg4|avi)$/i
      file = data.files[0]
      if types.test(file.type) || types.test(file.name)
        data.context = $(tmpl("template-avatar", file))
        $('#new_item').append(data.context)
        $('.actions input[type="submit"]').click (e) ->
          data.submit()
          e.preventDefault()           
      else
        alert("#{file.name} is not a gif, jpg or png image file")
    progress: (e, data) ->
      if data.context
        progress = parseInt(data.loaded / data.total * 100, 10)
        data.context.find('.bar').css('width', progress + '%')
    done: (e, data) ->
      $('.actions input[type="submit"]').off('click')

**application.js**

    //= require jquery
    //= require jquery_ujs
    //= require jquery.ui.all
    //= require bootstrap-sprockets
    //= require jquery.easy-autocomplete
    //= require jquery-fileupload
    //= require turbolinks
    //= require_tree .

**Error Message**

    ItemsController#create is missing a template for this request format and variant.
    request.formats: ["text/html"]
    request.variant: []
    raise ActionController::UnknownFormat, message
      elsif interactive_browser_request?
        message = "#{self.class.name}\##{action_name} is missing a template " \
          "for this request format and variant.\n\n" \
          "request.formats: #{request.formats.map(&:to_s).inspect}\n" \
          "request.variant: #{request.variant.inspect}\n\n" \

**Comment by 5minpause** [comment]
@OmarZV thanks for the kind words. That's a bummer, that it doesn't work for you. The repo and my code are quite old by now and I haven't actively used it for a few years already… with that out of the way, let's see…

The error message tells me, that you send a request with the format text/html. You are supposed to send a javascript request though. Your JS code does not work the way it's intended to, as far as I know.

The problem is, that it's quite hard for me to debug. There might be changes in the jquery-fileupload library or the jquery version you are using does work differently. I would suggest you play around with the js code until you submit a JS request, not a text/html request. That should advance you.
Does that make sense?

**Comment by OmarZV** [comment]
Makes perfect sense Holger I'll play around with the js code for sure, thank you again mate!!
