### ISSUE TITLE
File upload in small chunks

### ISSUE THREAD

**Issue by joseluistorres** [5minpause/multiple-file-upload#8]
Has anyone worked with the maxChunSize for a RoR app?

**Comment by 5minpause** [comment]
I haven’t.
A short Google reveals this: https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads
Have you tried this?

**Comment by joseluistorres** [comment]
Thanks @5minpause I did, but I need to implement something different to handle it. thanks again for replying!

**Comment by 5minpause** [comment]
You're welcome. If there are some implementation details you can't work out on your own, feel free to ping me again.
