### ISSUE TITLE
how can I modify this to upload wav files as well

### ISSUE THREAD

**Issue by hakehuang** [5minpause/multiple-file-upload#9]
I change the upload.rb and add below

```
 "audio/wav"
```

also I change the upload.js.coffee

```
types = /(\.|\/)(gif|jpe?g|png|mov|mpeg|mpeg4|avi|wav)$/i
```

but is seems still can not work

seems the Paperclip is not for audio, am i right?

**Comment by 5minpause** [comment]
Hi @hakehuang 
Thanks for your question. I'll need to take a look at it.
- Do you see any error messages in your log when the upload record should be created?
- Did you take a look at the paperclip docs if wav files are possible?
- What did Google say about it?
